// Environment loader for client-side applications
// This script should be generated by a build process that reads .env files

(function () {
  "use strict";

  // Environment configuration
  // In production, these values should be injected by your build process
  // and the API key should be properly secured
  function loadEnvironment() {
    // Check if we're in a development environment
    const isDev =
      window.location.hostname === "localhost" ||
      window.location.hostname === "127.0.0.1" ||
      window.location.protocol === "file:";

    // Check if we're on Vercel
    const isVercel =
      window.location.hostname.includes(".vercel.app") ||
      window.location.hostname.includes("vercel.app");

    let envVars = {
      NODE_ENV: isDev ? "development" : "production",
      DEBUG_MODE: isDev ? "true" : "false",
    };

    // Load API key based on environment
    if (isDev) {
      // Development: Load from localStorage or prompt user
      const apiKey =
        localStorage.getItem("GOOGLE_AI_API_KEY") ||
        prompt("Please enter your Google AI API Key for development:") ||
        "";

      if (apiKey) {
        localStorage.setItem("GOOGLE_AI_API_KEY", apiKey);
        envVars.GOOGLE_AI_API_KEY = apiKey;
      }
    } else if (isVercel) {
      // Vercel production: API key should be set via environment variables
      // This will be injected during build time or fetched from API
      console.log(
        `🔍 Vercel environment detected. VERCEL_ENV_GOOGLE_AI_API_KEY available: ${
          window.VERCEL_ENV_GOOGLE_AI_API_KEY ? "YES" : "NO"
        }`
      );
      envVars.GOOGLE_AI_API_KEY = window.VERCEL_ENV_GOOGLE_AI_API_KEY || "";
      if (envVars.GOOGLE_AI_API_KEY) {
        console.log(
          `✅ API Key loaded: ${envVars.GOOGLE_AI_API_KEY.substring(0, 10)}...`
        );
      } else {
        console.error(
          `❌ No API key found in window.VERCEL_ENV_GOOGLE_AI_API_KEY`
        );
      }
    } else {
      // Other production environments
      envVars.GOOGLE_AI_API_KEY = window.GOOGLE_AI_API_KEY || "";
    }

    // Make environment variables available
    window.ENV = envVars;
    console.log("🔧 window.ENV set to:", envVars);

    // Compatibility with Node.js-style process.env
    if (typeof window.process === "undefined") {
      window.process = { env: envVars };
    } else {
      window.process.env = { ...window.process.env, ...envVars };
    }

    console.log("🔧 Environment loaded:", isDev ? "development" : "production");

    return envVars;
  }

  // Initialize environment
  loadEnvironment();
})();
